// <auto-generated />
namespace Arpgo.Basketball.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class playerUpdateNumberNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(playerUpdateNumberNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201605142124374_playerUpdateNumberNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
